exercise-book/src/simple-db.md, exercise-solutions/simple_db/step2/src/lib.rs, exercise-solutions/simple_db/step4a/src/lib.rs, exercise-solutions/simple_db/step4e/src/lib.rs
Just to improve consistency between steps.
=> Minor changes to simple-db.

.github/workflows/build.yml, build.sh, describe.sh
Borrows from rust-training #69, but our build script is a little more complicated.
=> Use a slug as the output name.

exercise-book/src/shapes.md
=> Fix typo in shapes.md

exercise-book/src/rustlatin.md
Mostly changes the structure of the page so it is easier to read.
=> Exercise: rustlatin formatting

exercise-book/src/simple-db.md
=> Update simple-db.md - format Error variants as code

exercise-book/src/nrf52-usb-unknown-requests.md, exercise-book/src/nrf52-usb-updating-device-state.md
=> Last few fixes.

exercise-book/src/nrf52-radio-puzzle-help.md, exercise-book/src/nrf52-usb-get-descriptor-config-response.md, nrf52-code/hal-app/Cargo.toml, nrf52-code/radio-app/Cargo.lock, nrf52-code/radio-app/Cargo.toml
* Update heapless to 0.8
* Update docs to not talk about old, weird, heapless numbers-as-types stuff
Fixes: #50
=> Update heapless help

exercise-book/src/self-check.md
=> adds link to tools / tcp-client

exercise-solutions/rustlatin/step1/src/lib.rs, exercise-solutions/rustlatin/step2/src/lib.rs, exercise-solutions/rustlatin/step3/src/lib.rs, exercise-solutions/rustlatin/step4/src/lib.rs, exercise-templates/rustlatin/step1/src/lib.rs, exercise-templates/rustlatin/step2/src/lib.rs, exercise-templates/rustlatin/step3/src/lib.rs, exercise-templates/rustlatin/step4/src/lib.rs
=> Hide rustlatin warnings.

exercise-book/src/nrf52-usb-usb-enumeration.md
closes https://github.com/ferrous-systems/rust-exercises/issues/73
=> remove miro link

exercise-book/src/nrf52-radio-puzzle.md, exercise-book/src/nrf52-troubleshoot-usb-dongle.md, nrf52-code/usb-lib-solutions/get-descriptor-config/build.rs, nrf52-code/usb-lib-solutions/get-device/build.rs, nrf52-code/usb-lib-solutions/set-config/build.rs, nrf52-code/usb-lib/build.rs
We no longer supply nousb images. I will supply them on demand.
Also includes #109 because that fixes the build.
Closes #108
=> Stop talking about dongle images with nousb

exercise-book/src/rustlatin.md
- add full example
- remove redundant para
=> Add an example of rustlatin

exercise-book/src/nrf52-code-organisation.md, exercise-book/src/nrf52-hal-buttons.md, exercise-book/src/nrf52-tools.md
Allow install steps to be copy-pasted, and fix directory name.
Closes #129
Closes #130
=> Minor updates to nrf52 instructions.

exercise-book/src/nrf52-tools.md
It's important to add a confirmation step here, so folks can distinguish what looks like it works from what looks like it doesn't. 
We could add a "something like this, differing by OS, terminal setup, etc disclaimer" if you think it necessary.
=> Add tools final step confirmation

exercise-book/src/nrf52-hardware.md, exercise-book/src/nrf52-preparation.md, exercise-book/src/nrf52-tools.md
- refactored OS specific installation instructions
- moved DK section to before dongle section 
- removed some unnecessary duplication
- introduced some duplication for extra clarity in the installation instructions
=> Refactor OS specific requirements and tools

exercise-book/src/nrf52-hardware.md, exercise-book/src/nrf52-preparation.md, exercise-book/src/nrf52-tools.md
A clone of #141, so Cloudflare can see it and build it.
DO NOT MERGE. Merge #141 instead.
=> Draft: Requirements

.github/workflows/build.yml
We have deny(warnings) and 1.83 has new warnings. I'll fix these properly later.
=> Pin Rust to 1.82.

exercise-book/src/nrf52-usb-usb-endpoints.md
=> fix usb specification link

exercise-book/src/nrf52-hal-buttons.md, exercise-book/src/nrf52-radio-collision-avoidance.md, exercise-book/src/nrf52-radio-from-scratch.md, exercise-book/src/nrf52-references-resources.md, exercise-book/src/nrf52-usb-setup-stage.md
=> Update nordic links

nrf52-code/boards/dk-solution/Cargo.toml, nrf52-code/boards/dk/Cargo.toml, nrf52-code/boards/dongle/Cargo.toml, nrf52-code/usb-app-solutions/Cargo.toml, nrf52-code/usb-app/Cargo.toml, nrf52-code/usb-lib-solutions/complete/Cargo.toml, nrf52-code/usb-lib-solutions/get-descriptor-config/Cargo.toml, nrf52-code/usb-lib-solutions/get-device/Cargo.toml, nrf52-code/usb-lib-solutions/set-config/Cargo.toml, nrf52-code/usb-lib/Cargo.toml, xtask/Cargo.toml
Ran locally to make sure code didn't break.
Fixes #117 .
=> bump editions to 2021

nrf52-code/usb-lib/src/lib.rs
=> remove links to old website

exercise-book/src/simple-db.md
=> add note about different order affecting solution in simple-db

exercise-book/src/nrf52-usb-stack-overflow-protection.md
=> credit FS with writing flip-link

justfile
=> Remove QEMU code from nrf52 build.

nrf52-code/hal-app/.gitignore, nrf52-code/hal-app/.vscode/settings.json, nrf52-code/hal-app/hal-app.sublime-project, nrf52-code/radio-app/.gitignore, nrf52-code/radio-app/.vscode/settings.json, nrf52-code/radio-app/radio-app.sublime-project, nrf52-code/usb-app-solutions/.gitignore, nrf52-code/usb-app-solutions/.vscode/settings.json, nrf52-code/usb-app-solutions/usb-app-solutions.sublime-project, nrf52-code/usb-app/.gitignore, nrf52-code/usb-app/.vscode/settings.json, nrf52-code/usb-app/usb-app.sublime-project, qemu-code/uart-driver/.gitignore, qemu-code/uart-driver/.vscode/settings.json, qemu-code/uart-driver/uart-driver.sublime-project
Fixes VS Code and Sublime Text when looking at the embedded projects.
=> Fix IDE settings

exercise-book/src/nrf52-radio-using-hal.md, nrf52-code/boards/dongle/Cargo.lock, nrf52-code/boards/dongle/Cargo.toml, nrf52-code/boards/dongle/src/lib.rs, nrf52-code/hal-app/Cargo.toml, nrf52-code/loopback-fw/Cargo.lock, nrf52-code/loopback-fw/Cargo.toml, nrf52-code/loopback-fw/src/main.rs, nrf52-code/puzzle-fw/Cargo.lock, nrf52-code/puzzle-fw/Cargo.toml, nrf52-code/puzzle-fw/src/main.rs, nrf52-code/radio-app/.cargo/config.toml, nrf52-code/radio-app/Cargo.lock, nrf52-code/radio-app/Cargo.toml, nrf52-code/usb-app/Cargo.lock, nrf52-code/usb-app/Cargo.toml
=> a lot of smaller improvements
