ferrous-systems/rust-exercises

exercise-book/src/SUMMARY.md
exercise-book/src/simple-db-knowledge.md
exercise-book/src/simple-db-solution.md
exercise-book/src/simple-db.md
exercise-solutions/connected-mailbox/simple-db/src/lib.rs
exercise-solutions/simple-db/step2/src/lib.rs
exercise-solutions/simple-db/step4a/src/lib.rs
exercise-solutions/simple-db/step4b/src/lib.rs
exercise-solutions/simple-db/step4c/src/lib.rs
exercise-solutions/simple-db/step4d/src/lib.rs
exercise-solutions/simple-db/step4e/src/lib.rs

The late trim() would allow some invalid inputs. Also, let's not handle the impossible case of splitn never returning anything.

Simplify the simple-db.

---

exercise-solutions/connected-mailbox/tcp-server/src/main.rs
exercise-templates/tcp-echo-server/src/main.rs

1) A bad command from the user isn't an error the main thread needs to handle - that can go back to the client.
2) So you don't need the combo ServerError type.
3) Don't break read_command out - it prevents you accessing the string form of the command.
4) Move things around to tcp-echo-server and connected-mailbox/tcp-server look alike.
5) Add a short timeout, so slow clients can't lock us up for long periods.
Closes #20

Clean up the connected-db example.

---

exercise-solutions/simple-db/step4a/src/lib.rs

Solution Step 4a for simpleDB had the tests copy-pasted twice.

Remove duplicate tests.

---

exercise-book/src/fizzbuzz.md

Absolute URLs don't work when looking at rendered output in a browser.

Update fizzbuzz.md to remove absolute URL

---

exercise-book/src/self-check.md

* Use "you" not "we" because this is to be completed alone, not in a training.
* Note that input is UTF-8.
* Add optional task to deal with timeouts.

Adjust wording for the self-test.

---

.github/workflows/build.yml

Older ones used node.js 16 which is not supported. This causes a warning annotation on the Job Summary page.

Update github actions to node.js 20 versions

---

exercise-book/src/SUMMARY.md

* Move the generic stuff up before the USB workshop
* Add some sub-headings - they are ignored by mdbook but appear in github
Now you can share URLs like https://github.com/ferrous-systems/rust-exercises/blob/21adb657d5dea01b940166e608d9cfbaffbd65dc/exercise-book/src/SUMMARY.md#nrf52-radio-workbook, which takes you to the summary rather than dropping you into a specific chapter (which makes the summary invisible when reading on Github)

Clean up summary for embedded exercises

---

nrf52-code/boards/dk-solution/Cargo.toml
nrf52-code/boards/dk-solution/src/lib.rs
nrf52-code/boards/dk-solution/src/usbd.rs
nrf52-code/boards/dk/Cargo.toml
nrf52-code/boards/dk/src/lib.rs
nrf52-code/boards/dk/src/usbd.rs
nrf52-code/hal-app/Cargo.lock
nrf52-code/radio-app/Cargo.lock
nrf52-code/usb-app-solutions/Cargo.lock
nrf52-code/usb-app/Cargo.lock

Remove `static mut` values, our references to which were going to cause a warning in the next Rust release.
Uses the grounded crate, and a custom wrapper to make an !Sync type Sync.
Closes: #84

Removed use of static mut.

---

nrf52-code/loopback-fw/src/main.rs
nrf52-code/puzzle-fw/src/main.rs

Closes [#156](https://github.com/ferrous-systems/rust-training/issues/156)

Modify dongle firmware to correctly report as an IAD device.

---

qemu-code/uart-driver/src/main.rs

I had moved the start-up code but still pointed to the old location.

QEMU UART example: typo fix

---

exercise-book/src/nrf52-tools.md

The old instructions don't work with the new 0.24 version of probe-rs.

Switch the install instructions for probe-rs.

---

.gitignore
_redirects
cloudflare.sh

Builds all versions, like with the training.
Relative links are changed to point to the source code on Github.

Add cloudflare build script.

---

build.sh
exercise-book/src/nrf52-hardware.md
exercise-book/src/nrf52-radio-dongle.md
exercise-book/src/nrf52-tools.md
exercise-book/src/nrf52-usb-data-stage.md
exercise-book/src/nrf52-usb-idle-state.md
exercise-book/src/nrf52-usb-listing-usb-devices.md
nrf52-code/usb-app-solutions/Cargo.lock
nrf52-code/usb-app-solutions/Cargo.toml
nrf52-code/usb-lib-solutions/complete/.gitignore
nrf52-code/usb-lib-solutions/complete/Cargo.toml
nrf52-code/usb-lib-solutions/complete/src/lib.rs
nrf52-code/usb-lib-solutions/get-descriptor-config/build.rs
nrf52-code/usb-lib-solutions/get-device/Cargo.toml
nrf52-code/usb-lib-solutions/get-device/build.rs
nrf52-code/usb-lib-solutions/set-config/Cargo.toml
nrf52-code/usb-lib-solutions/set-config/build.rs
nrf52-code/usb-lib/build.rs

Replaces `cargo xtask usb-list` with `cyme`, which looks much nicer.
Also adds a completed usb-lib solution for the completed usb-apps to use.
Fixes #113
Fixes #112

Suggest cyme

---

exercise-book/src/fizzbuzz.md
nrf52-code/usb-lib-solutions/get-descriptor-config/build.rs
nrf52-code/usb-lib-solutions/get-device/build.rs
nrf52-code/usb-lib-solutions/set-config/build.rs
nrf52-code/usb-lib/build.rs

Prefer `format!` over `.to_string()` and don't introduce `String::from(...)` because it doesn't work with integers.
Fixes #106

Clean up fizzbuzz.

---

nrf52-code/usb-lib-solutions/get-descriptor-config/build.rs
nrf52-code/usb-lib-solutions/get-device/build.rs
nrf52-code/usb-lib-solutions/set-config/build.rs
nrf52-code/usb-lib/build.rs

Rust got much fussier about these in 1.80. See https://blog.rust-lang.org/2024/05/06/check-cfg.html.
Closes: #110

Allow our use of cfg(TODO).

---

exercise-book/src/simple-db-knowledge.md
exercise-book/src/simple-db-solution.md
exercise-book/src/simple-db.md

- why do we split things into files here (only?)
- Is it worth talking about why we choose the order we do in the algothrithm in 4.x? 
- in L62 of `simple-db.m`: 
> 4. Empty payloads are allowed. In this case, the command is
`PUBLISH \n`.
Does this mean if the payload is emppty the command is determined to be PUBLISH. Or does it mean that only PUBLISH can have an empty payload.

Minor edits

---

exercise-book/src/nrf52-usb-usb-events.md
nrf52-code/usb-app-solutions/src/bin/usb-1.rs
nrf52-code/usb-app-solutions/src/bin/usb-2.rs
nrf52-code/usb-app-solutions/src/bin/usb-3.rs
nrf52-code/usb-app-solutions/src/bin/usb-4.rs
nrf52-code/usb-app-solutions/src/bin/usb-5.rs
nrf52-code/usb-app/src/bin/usb-1.rs
nrf52-code/usb-app/src/bin/usb-2.rs
nrf52-code/usb-app/src/bin/usb-3.rs
nrf52-code/usb-app/src/bin/usb-4.rs

The name 'main' is just confusing.
Closes #132

Rename USB interrupt handler.

---

.github/workflows/build.yml
exercise-book/src/nrf52-radio-dongle.md
exercise-book/src/nrf52-radio-puzzle.md

Adding the dongle firmware to the release area saves people from having to download the whole release zip file when they'd rather work from the git checkout.

Add Dongle FW to release area

---

exercise-book/src/green-yellow-game.md
exercise-solutions/green-yellow/src/bin/complete.rs
exercise-solutions/green-yellow/src/bin/step4.rs
exercise-solutions/green-yellow/src/bin/step5.rs
exercise-solutions/green-yellow/src/bin/step6.rs

Ooops - found a case our solution didn't handle.
Also re-wrote the solution to hopefully be easier to read.
And, `std::random` is coming!

Fix green yellow tests

---

.github/workflows/build.yml

make build run weekly on mondays, skip if in PR

---

.github/workflows/weekly-canary-build.yml
exercise-solutions/connected-mailbox/Cargo.lock
exercise-solutions/multi-threaded-mailbox/Cargo.lock

This PR involves 2 small changes:
1. It bumps the `proc-macro2` dependency to one that doesn't break on [nightly](https://github.com/jonasbb/serde_with/pull/609/files) (This was a well [documented break then](https://github.com/rust-lang/rust/issues/113152).)
2. It adds a `fail-fast: false` argument to the weekly canary to make it so if one stable/beta/nightly fails the other jobs still run.
Should fix #168

bump proc-macro2 dep to pass nightly tests and add fail-fast-false

---

.github/workflows/build.yml
.github/workflows/weekly-canary-build.yml

Our jobs will start [failing in a month](https://github.com/actions/runner-images/issues/11101) unless we update.
Let's try 24.04 to see if everything works, else go for 22.04.

update github actions to ubuntu-24.04

---

.github/workflows/build.yml

This adds the `rust-cache` GitHub Action to the repo.
The reason why I want to add this as a small PR is that subsequent PRs made to the repo can modify said caching logic and we can thus see how efficient different batching strategies can be, but we need to setup the cache first.

add rust-cache to CI

---

exercise-book/src/SUMMARY.md
exercise-book/src/building-linux-kernel-driver.md

Adds an exercise where we compile a Linux kernel with Rust support (for AArch64 or x86-64), and boot a VM using it. We can then write kernel modules in Rust and load them into our kernel.
TODO: Write add a solution for the chardev exercise.

Rust for Linux exercise.

---

exercise-book/src/building-linux-kernel-driver.md

Add `ioctl` required feature for `nix` crate in Linux kernel exercise.
Without this feature, the example code will not compile.

Add ioctl required feature for nix crate in Linux kernel exercise

---

exercise-book/src/building-linux-kernel-driver.md

Tell people where to find EDK2 in their QEMU install directory, rather than downloading random blobs from a Github gist.

Actually, homebrew does ship EDK2 with qemu-system-aarch64

---

.github/workflows/parallel-build.yml
build.sh
build_fns.sh

The previous structure of this workflow (.yml file) did not invoke the `Swatinem/rust-cache` with the appropriate workspace per job.
Let's leverage that for even more speedups 🏁 
Should fix #195

Invoke proper caching on CI

---

nrf52-code/boards/dongle/memory.x

We never got near the limit, but it's important we don't one day accidentally trash the bootloader top-half at 0x000E_0000.
Should have zero effect on the resulting binary at this time.

Limit dongle flash usage.

---

qemu-code/uart-driver/criticalup.toml

Ferrocene 25.05 is the next release - updating to check everything still works.

Update all criticalup.toml files to use Ferrocene 25.05
